# Generated by Django 5.2 on 2025-05-12 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_company_slide_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppt', models.CharField(choices=[('accept', 'Accept'), ('discard', 'Discard')], default='accept', max_length=10)),
                ('request_access', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=5)),
                ('company_permission', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], db_column='company_permission', default='no', max_length=3)),
                ('user_intro', models.TextField(blank=True, null=True)),
                ('user_purpose', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_permission',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
