# Generated by Django 5.2 on 2025-05-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.TextField()),
                ('transaction_id', models.TextField(unique=True)),
                ('payment_status', models.TextField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')])),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'companies_payment',
                'managed': False,
            },
        ),
    ]
