# Generated by Django 5.2 on 2025-05-22 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_reason', models.TextField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(db_column='deleted_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_control', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Control',
                'verbose_name_plural': 'User Controls',
                'db_table': 'user_control',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
