# Generated by Django 5.2 on 2025-05-23 15:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0003_customuser_delete_usercontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reset_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
