# Generated by Django 5.2 on 2025-05-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0004_alter_customuser_reset_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(default='Country', max_length=100),
        ),
    ]
