# Generated by Django 5.2 on 2025-05-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyevent',
            options={'managed': False, 'ordering': ['-start_at']},
        ),
    ]
