# Generated by Django 5.2 on 2025-05-06 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_companyevent_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='companyevent',
            table='company_event',
        ),
    ]
