# Generated by Django 4.2.7 on 2025-04-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('expense_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('completion_percentage', models.IntegerField()),
                ('expense_percentage', models.IntegerField()),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_remaining', models.DateField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='project_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
