# Generated by Django 5.1.6 on 2025-05-26 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Discussion', 'Discussion'), ('Project Update', 'Project Update'), ('Question', 'Question'), ('Idea', 'Idea'), ('Other', 'Other'), ('Event', 'Event')], max_length=32)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=300)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='community_attachments/')),
                ('eventLocation', models.CharField(blank=True, max_length=200)),
                ('eventLocationLink', models.URLField(blank=True)),
                ('eventStartDateTime', models.DateTimeField(blank=True, null=True)),
                ('eventEndDateTime', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community_backend.communitypost')),
            ],
        ),
    ]
