# Generated by Django 5.1.6 on 2025-05-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Discussion', 'Discussion'), ('Project Update', 'Project Update'), ('Question', 'Question'), ('Idea', 'Idea'), ('Other', 'Other'), ('Event', 'Event')], max_length=32)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=300)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='community_attachments/')),
                ('eventLocation', models.CharField(blank=True, max_length=200)),
                ('eventLocationLink', models.URLField(blank=True)),
                ('eventStartDateTime', models.DateTimeField(blank=True, null=True)),
                ('eventEndDateTime', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
