# Generated by Django 5.1.6 on 2025-05-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_backend', '0002_communityinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitycomment',
            name='read',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='communityinterest',
            name='read',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=3),
        ),
    ]
