// 100+ Q&A pairs for Innovest chatbot
const chatbotQA = [
  // About
  { q: 'what is innovest', a: 'Innovest is a platform that connects startups with investors for crowdfunding and growth.' },
  { q: 'who can use innovest', a: 'Both startup founders and investors can use Innovest to raise funds or invest in new ventures.' },
  { q: 'is innovest free', a: 'Creating an account is free. We charge a small fee on successful fundraising.' },
  { q: 'where is innovest based', a: 'Innovest is a global platform accessible from anywhere.' },
  { q: 'how does innovest work', a: 'Startups create campaigns, investors browse and invest, and Innovest facilitates secure transactions.' },
  { q: 'what makes innovest different', a: 'We offer a user-friendly platform, strong community, and robust security for both startups and investors.' },
  // Account
  { q: 'how do i create an account', a: 'Click Sign Up and fill in your details to create an account.' },
  { q: 'how do i reset my password', a: 'Click Forgot Password on the login page and follow the instructions.' },
  { q: 'how do i delete my account', a: 'Contact support to request account deletion.' },
  { q: 'can i change my email', a: 'Yes, go to your profile settings to update your email address.' },
  { q: 'how do i update my profile', a: 'Go to your dashboard and click Edit Profile.' },
  { q: 'can i have multiple accounts', a: 'We recommend one account per user for security and compliance.' },
  { q: 'how do i verify my email', a: 'Check your inbox for a verification email after signing up.' },
  { q: 'i did not receive a verification email', a: 'Check your spam folder or request a new verification email from the login page.' },
  { q: 'how do i change my password', a: 'Go to settings and select Change Password.' },
  // Investing
  { q: 'how do i invest', a: 'Sign up as an investor, browse campaigns, and follow the steps to invest.' },
  { q: 'what is the minimum investment', a: 'The minimum investment varies by campaign, but is usually $100.' },
  { q: 'how do i track my investments', a: 'Go to your dashboard to see all your investments and their status.' },
  { q: 'can i invest in multiple startups', a: 'Yes, you can invest in as many campaigns as you like.' },
  { q: 'how do i withdraw returns', a: 'Returns are credited to your account. You can withdraw them to your bank or payment method.' },
  { q: 'are investments guaranteed', a: 'No investment is risk-free. Please review each campaign carefully.' },
  { q: 'can i cancel an investment', a: 'Investments are usually final, but contact support for special cases.' },
  { q: 'do i get equity', a: 'Some campaigns offer equity, others offer rewards. Check the campaign details.' },
  { q: 'how do i know if a startup is legit', a: 'We perform KYC and due diligence, but always do your own research.' },
  // Fundraising
  { q: 'how do i start a campaign', a: 'Sign up as a founder, complete your profile, and click Start a Fundraise.' },
  { q: 'what documents are required', a: 'You need a business plan, pitch deck, and identity verification.' },
  { q: 'how do i edit my campaign', a: 'Go to your dashboard, select your campaign, and click Edit.' },
  { q: 'can i cancel my campaign', a: 'Contact support to cancel a campaign.' },
  { q: 'how do i set a funding goal', a: 'You can set your funding goal when creating your campaign.' },
  { q: 'can i raise funds in multiple rounds', a: 'Yes, you can launch new rounds after completing one.' },
  { q: 'how do i share my campaign', a: 'Use the Share button on your campaign page to share on social media or via link.' },
  { q: 'how do i update investors', a: 'Post updates from your campaign dashboard to keep investors informed.' },
  { q: 'what happens if i do not reach my goal', a: 'Funds may be returned to investors or partially disbursed, depending on campaign terms.' },
  // Security & Privacy
  { q: 'is my data secure', a: 'Yes, we use industry-standard security practices to keep your data safe.' },
  { q: 'how do you use my data', a: 'We use your data to provide services and never sell it to third parties.' },
  { q: 'can i make my profile private', a: 'You can adjust your privacy settings in your profile.' },
  { q: 'how do you verify users', a: 'We use KYC and AML checks to verify all users.' },
  { q: 'what is kyc', a: 'KYC stands for Know Your Customer, a process to verify your identity.' },
  { q: 'what is aml', a: 'AML stands for Anti-Money Laundering, a process to prevent illegal activity.' },
  { q: 'how do i report a security issue', a: 'Contact support immediately if you notice any suspicious activity.' },
  // Payments
  { q: 'what payment methods are accepted', a: 'We accept credit/debit cards, bank transfers, and select e-wallets.' },
  { q: 'how do i withdraw funds', a: 'Go to your dashboard and select Withdraw to transfer funds to your bank.' },
  { q: 'are there any fees', a: 'We charge a small platform fee on successful fundraising. See our Pricing page.' },
  { q: 'how long do withdrawals take', a: 'Withdrawals are processed within 3-5 business days.' },
  { q: 'can i use paypal', a: 'Currently, we do not support PayPal. Please use other payment methods.' },
  { q: 'how do i view my payment history', a: 'Go to your dashboard and select Payment History.' },
  // Support
  { q: 'how do i contact support', a: 'You can contact support via the Contact Us page or email us at innovest05@gmail.com.' },
  { q: 'where can i find the faq', a: 'The FAQ is available in the Resources section of our website.' },
  { q: 'how do i report a bug', a: 'Use the Contact Us form and select Bug Report as the subject.' },
  { q: 'how do i give feedback', a: 'We welcome feedback! Use the Contact Us form or email us.' },
  { q: 'do you offer live chat', a: 'Currently, we offer support via email and contact form.' },
  // Community
  { q: 'how do i join the community', a: 'Sign up and participate in discussions in the Community tab.' },
  { q: 'can i message other users', a: 'Yes, you can send messages to other users from their profile page.' },
  { q: 'how do i report inappropriate content', a: 'Click Report on the post or message, or contact support.' },
  { q: 'can i follow startups', a: 'Yes, click Follow on a startup profile to get updates.' },
  { q: 'how do i join a group', a: 'Groups are available in the Community section. Click Join to participate.' },
  // Events
  { q: 'how do i join an event', a: 'Go to the Events tab and click Join on any event you are interested in.' },
  { q: 'can i host an event', a: 'Yes, founders can propose and host events. Contact support for details.' },
  { q: 'are events free', a: 'Most events are free, but some may require a ticket or registration.' },
  { q: 'how do i get event reminders', a: 'Register for an event to receive email reminders.' },
  { q: 'can i watch event recordings', a: 'Recordings are available after the event in the Events section.' },
  // Legal
  { q: 'what are the terms of service', a: 'You can read our Terms of Service in the Legal section of our website.' },
  { q: 'where is the privacy policy', a: 'Our Privacy Policy is linked in the footer and Legal section.' },
  { q: 'how do you handle disputes', a: 'Contact support for dispute resolution. We aim to resolve all issues fairly.' },
  { q: 'is innovest regulated', a: 'We comply with all applicable laws and regulations.' },
  // General Usage
  { q: 'how do i change my email', a: 'Go to your profile settings to update your email address.' },
  { q: 'can i use innovest on mobile', a: 'Yes, our platform is mobile-friendly and works on all devices.' },
  { q: 'how do i subscribe to updates', a: 'Subscribe to our newsletter from your dashboard or the homepage.' },
  { q: 'can i invite friends', a: 'Yes, use the Invite Friends feature in your dashboard.' },
  { q: 'how do i delete a post', a: 'Go to your post, click the options menu, and select Delete.' },
  { q: 'how do i edit a post', a: 'Go to your post, click the options menu, and select Edit.' },
  { q: 'how do i block a user', a: 'Go to their profile and click Block User.' },
  { q: 'how do i unblock a user', a: 'Go to your settings and manage your blocked users.' },
  { q: 'can i change my username', a: 'Currently, usernames cannot be changed after registration.' },
  { q: 'how do i enable two-factor authentication', a: 'Go to security settings and enable 2FA for extra protection.' },
  { q: 'what browsers are supported', a: 'Innovest works on all modern browsers including Chrome, Firefox, Safari, and Edge.' },
  { q: 'how do i log out', a: 'Click your profile icon and select Log Out.' },
  { q: 'can i pause my campaign', a: 'Contact support to request a campaign pause.' },
  { q: 'how do i get notifications', a: 'Enable notifications in your profile settings.' },
  { q: 'how do i upload documents', a: 'Go to your campaign or profile and use the Upload button.' },
  { q: 'can i use a pseudonym', a: 'You must use your real name for compliance, but you can set a display name.' },
  { q: 'how do i reset my 2fa', a: 'Contact support to reset your two-factor authentication.' },
  { q: 'how do i see trending startups', a: 'Visit the Browse Companies section and filter by Trending.' },
  { q: 'how do i see recently funded startups', a: 'Visit the Browse Companies section and filter by Recently Funded.' },
  { q: 'how do i see new startups', a: 'Visit the Browse Companies section and filter by New & Noteworthy.' },
  { q: 'how do i get a pitch reviewed', a: 'Submit your pitch in the campaign creation process for review.' },
  { q: 'can i get mentoring', a: 'Mentoring is available for select campaigns. Contact support for more info.' },
  { q: 'how do i access analytics', a: 'Go to your dashboard and select Analytics.' },
  { q: 'how do i export my data', a: 'Contact support to request a data export.' },
  { q: 'how do i close my account', a: 'Contact support to close your account permanently.' },
  { q: 'how do i change my notification settings', a: 'Go to your profile and select Notification Settings.' },
  { q: 'how do i get help with taxes', a: 'Consult a tax advisor. We provide basic tax info in our Help section.' },
  { q: 'can i use innovest internationally', a: 'Yes, Innovest is available worldwide.' },
  { q: 'how do i set my timezone', a: 'Set your timezone in your profile settings.' },
  { q: 'how do i get a refund', a: 'Contact support to request a refund if eligible.' },
  { q: 'how do i see my transaction history', a: 'Go to your dashboard and select Payment History.' },
  { q: 'how do i update my company info', a: 'Go to your company profile and click Edit.' },
  { q: 'how do i add team members', a: 'Go to your company profile and use the Add Team Member button.' },
  { q: 'how do i remove a team member', a: 'Go to your company profile, select the member, and click Remove.' },
  { q: 'how do i change my company logo', a: 'Go to your company profile and click Change Logo.' },
  { q: 'how do i get featured', a: 'Contact support to learn about featured opportunities.' },
  { q: 'how do i access the mobile app', a: 'Our mobile app is coming soon. Use the web platform for now.' },
  { q: 'how do i get a certificate', a: 'Certificates are available for select events and achievements.' },
  { q: 'how do i join a webinar', a: 'Go to the Events section and register for upcoming webinars.' },
  { q: 'how do i get a mentor', a: 'Mentors are available for select campaigns. Contact support for more info.' },
  { q: 'how do i see my followers', a: 'Go to your profile to see your followers and following.' },
  { q: 'how do i see who liked my post', a: 'Click on the likes count on your post to see who liked it.' },
  { q: 'how do i turn off email notifications', a: 'Go to Notification Settings and disable email notifications.' },
  { q: 'how do i enable dark mode', a: 'Toggle dark mode in your profile or settings.' },
  { q: 'how do i get a receipt', a: 'Receipts are available in your Payment History.' },
  { q: 'how do i update my billing info', a: 'Go to Payment Settings to update your billing information.' },
  { q: 'how do i get a tax invoice', a: 'Tax invoices are available in your Payment History.' },
  { q: 'how do i set up a recurring investment', a: 'Recurring investments are coming soon. Stay tuned!' },
  { q: 'how do i get a referral bonus', a: 'Invite friends using your referral link to earn bonuses.' },
  { q: 'how do i see my referral stats', a: 'Referral stats are available in your dashboard.' },
  { q: 'how do i get a verification badge', a: 'Verification badges are awarded to verified users and companies.' },
  { q: 'how do i request a feature', a: 'Submit feature requests via the Contact Us form.' },
  { q: 'how do i report a scam', a: 'Report scams immediately to support with all details.' },
  { q: 'how do i get a press kit', a: 'Press kits are available on request. Contact support.' },
  { q: 'how do i get a media inquiry answered', a: 'Media inquiries can be sent to our press email.' },
  { q: 'how do i get a partnership', a: 'Partnerships are welcome! Contact us for collaboration.' },
  { q: 'how do i get a sponsorship', a: 'Sponsorship opportunities are available for select events.' },
  { q: 'how do i get a demo', a: 'Request a demo via the Contact Us page.' },
  { q: 'how do i get a whitepaper', a: 'Whitepapers are available in the Resources section.' },
  { q: 'how do i get a pitch template', a: 'Pitch templates are available in the Resources section.' },
  { q: 'how do i get a business plan template', a: 'Business plan templates are available in the Resources section.' },
  { q: 'how do i get a legal template', a: 'Legal templates are available in the Resources section.' },
  { q: 'how do i get a marketing kit', a: 'Marketing kits are available on request.' },
  { q: 'how do i get a startup checklist', a: 'Startup checklists are available in the Resources section.' },
  { q: 'how do i get a funding guide', a: 'Funding guides are available in the Resources section.' },
  { q: 'how do i get a valuation guide', a: 'Valuation guides are available in the Resources section.' },
  { q: 'how do i get a term sheet template', a: 'Term sheet templates are available in the Resources section.' },
  { q: 'how do i get a cap table template', a: 'Cap table templates are available in the Resources section.' },
  { q: 'how do i get a financial model template', a: 'Financial model templates are available in the Resources section.' },
  { q: 'how do i get a pitch video guide', a: 'Pitch video guides are available in the Resources section.' },
  { q: 'how do i get a branding guide', a: 'Branding guides are available in the Resources section.' },
  { q: 'how do i get a go-to-market guide', a: 'Go-to-market guides are available in the Resources section.' },
  { q: 'how do i get a customer discovery guide', a: 'Customer discovery guides are available in the Resources section.' },
  { q: 'how do i get a product roadmap template', a: 'Product roadmap templates are available in the Resources section.' },
  { q: 'how do i get a hiring guide', a: 'Hiring guides are available in the Resources section.' },
  { q: 'how do i get a remote work guide', a: 'Remote work guides are available in the Resources section.' },
  { q: 'how do i get a growth hacking guide', a: 'Growth hacking guides are available in the Resources section.' },
  { q: 'how do i get a sales guide', a: 'Sales guides are available in the Resources section.' },
  { q: 'how do i get a customer support guide', a: 'Customer support guides are available in the Resources section.' },
  { q: 'how do i get a pitch event invite', a: 'Pitch event invites are sent to selected startups. Watch your email!' },
  { q: 'how do i get a newsletter', a: 'Subscribe to our newsletter from your dashboard or homepage.' },
  { q: 'how do i get a startup story featured', a: 'Submit your story via the Contact Us page.' },
  { q: 'how do i get a founder interview', a: 'Founder interviews are by invitation. Contact support to express interest.' },
  { q: 'how do i get a user guide', a: 'User guides are available in the Help section.' },
  { q: 'how do i get a video tutorial', a: 'Video tutorials are available in the Help section.' },
  { q: 'how do i get a community badge', a: 'Community badges are awarded for active participation.' },
  { q: 'how do i get a leaderboard rank', a: 'Leaderboard ranks are based on your activity and contributions.' },
  { q: 'how do i get a startup award', a: 'Startup awards are given at select events and competitions.' },
  { q: 'how do i get a feedback form', a: 'Feedback forms are available in the Help section.' },
  { q: 'how do i get a support ticket', a: 'Submit a support ticket via the Contact Us page.' },
  { q: 'how do i get a bug bounty', a: 'Bug bounties are available for critical security reports.' },
  { q: 'how do i get a roadmap', a: 'Our product roadmap is available in the Resources section.' },
  { q: 'how do i get a changelog', a: 'Changelogs are published in the Updates section.' },
  { q: 'how do i get a release note', a: 'Release notes are published in the Updates section.' },
  { q: 'how do i get a press release', a: 'Press releases are available in the News section.' },
  { q: 'how do i get a media kit', a: 'Media kits are available on request.' },
  { q: 'how do i get a sponsorship proposal', a: 'Sponsorship proposals are available on request.' },
  { q: 'how do i get a partnership proposal', a: 'Partnership proposals are available on request.' },
  { q: 'how do i get a white label solution', a: 'Contact support to discuss white label solutions.' },
  { q: 'how do i get a custom integration', a: 'Custom integrations are available for enterprise clients.' },
  { q: 'how do i get a developer api', a: 'API access is available for select partners. Contact support.' },
  { q: 'how do i get a sandbox account', a: 'Sandbox accounts are available for testing. Contact support.' },
  { q: 'how do i get a beta invite', a: 'Beta invites are sent to selected users. Watch your email!' },
  { q: 'how do i get a product demo', a: 'Request a product demo via the Contact Us page.' },
  { q: 'how do i get a case study', a: 'Case studies are available in the Resources section.' },
  { q: 'how do i get a testimonial', a: 'Submit your testimonial via the Contact Us page.' },
  { q: 'how do i get a reference', a: 'References are available on request for select users.' },
  { q: 'how do i get a business introduction', a: 'Business introductions are available for select users.' },
  { q: 'how do i get a networking opportunity', a: 'Networking opportunities are available at events and in the Community.' },
  { q: 'how do i get a speaking slot', a: 'Speaking slots are available at select events. Contact support.' },
  { q: 'how do i get a booth at an event', a: 'Booth applications are available for select events.' },
  { q: 'how do i get a sponsorship package', a: 'Sponsorship packages are available on request.' },
  { q: 'how do i get a media partnership', a: 'Media partnerships are available for select partners.' },
  { q: 'how do i get a guest blog', a: 'Guest blog submissions are welcome. Contact support.' },
  { q: 'how do i get a podcast feature', a: 'Podcast features are available for select startups.' },
  { q: 'how do i get a video interview', a: 'Video interviews are available for select founders.' },
  { q: 'how do i get a product review', a: 'Product reviews are available for select startups.' },
  { q: 'how do i get a user survey', a: 'User surveys are sent periodically to gather feedback.' },
  { q: 'how do i get a market report', a: 'Market reports are available in the Resources section.' },
  { q: 'how do i get a trend analysis', a: 'Trend analyses are available in the Resources section.' },
  { q: 'how do i get a competitor analysis', a: 'Competitor analyses are available in the Resources section.' },
  { q: 'how do i get a valuation report', a: 'Valuation reports are available on request.' },
  { q: 'how do i get a due diligence checklist', a: 'Due diligence checklists are available in the Resources section.' },
  { q: 'how do i get a legal opinion', a: 'Legal opinions are available for select cases. Contact support.' },
  { q: 'how do i get a compliance guide', a: 'Compliance guides are available in the Resources section.' },
  { q: 'how do i get a risk assessment', a: 'Risk assessments are available for select campaigns.' },
  { q: 'how do i get a business valuation', a: 'Business valuations are available on request.' },
  { q: 'how do i get a funding report', a: 'Funding reports are available in the Resources section.' },
  { q: 'how do i get a pitch feedback', a: 'Pitch feedback is available from mentors and investors.' },
  { q: 'how do i get a startup audit', a: 'Startup audits are available for select companies.' },
  { q: 'how do i get a growth report', a: 'Growth reports are available in the Resources section.' },
  { q: 'how do i get a user analytics', a: 'User analytics are available in your dashboard.' },
  { q: 'how do i get a performance report', a: 'Performance reports are available in your dashboard.' },
  { q: 'how do i get a milestone update', a: 'Milestone updates are posted in your campaign dashboard.' },
  { q: 'how do i get a funding alert', a: 'Funding alerts are sent via email and notifications.' },
  { q: 'how do i get a campaign summary', a: 'Campaign summaries are available in your dashboard.' },
  { q: 'how do i get a user manual', a: 'User manuals are available in the Help section.' },
  { q: 'how do i get a support guide', a: 'Support guides are available in the Help section.' },
  { q: 'how do i get a troubleshooting guide', a: 'Troubleshooting guides are available in the Help section.' },
  { q: 'how do i get a contact list', a: 'Contact lists are available in your dashboard.' },
  { q: 'how do i get a startup directory', a: 'Startup directories are available in the Resources section.' },
  { q: 'how do i get a founder directory', a: 'Founder directories are available in the Resources section.' },
  { q: 'how do i get an investor directory', a: 'Investor directories are available in the Resources section.' },
  { q: 'how do i get a company directory', a: 'Company directories are available in the Resources section.' },
  { q: 'how do i get a partner directory', a: 'Partner directories are available in the Resources section.' },
  { q: 'how do i get a mentor directory', a: 'Mentor directories are available in the Resources section.' },
  { q: 'how do i get a service provider directory', a: 'Service provider directories are available in the Resources section.' },
  { q: 'how do i get a resource library', a: 'Resource libraries are available in the Resources section.' },
  { q: 'how do i get a knowledge base', a: 'Knowledge bases are available in the Help section.' },
  { q: 'how do i get a help center', a: 'The Help Center is available in the Resources section.' },
  { q: 'how do i get a support center', a: 'The Support Center is available in the Help section.' },
  { q: 'how do i get a learning center', a: 'The Learning Center is available in the Resources section.' },
  { q: 'how do i get a training center', a: 'The Training Center is available in the Resources section.' },
  { q: 'how do i get a webinar recording', a: 'Webinar recordings are available in the Events section.' },
  { q: 'how do i get a workshop recording', a: 'Workshop recordings are available in the Events section.' },
  { q: 'how do i get a conference recording', a: 'Conference recordings are available in the Events section.' },
  { q: 'how do i get a summit recording', a: 'Summit recordings are available in the Events section.' },
  { q: 'how do i get a bootcamp recording', a: 'Bootcamp recordings are available in the Events section.' },
  { q: 'how do i get a hackathon recording', a: 'Hackathon recordings are available in the Events section.' },
  { q: 'how do i get a pitch competition recording', a: 'Pitch competition recordings are available in the Events section.' },
  { q: 'how do i get a demo day recording', a: 'Demo Day recordings are available in the Events section.' },
  { q: 'how do i get a fireside chat recording', a: 'Fireside chat recordings are available in the Events section.' },
  { q: 'how do i get a panel discussion recording', a: 'Panel discussion recordings are available in the Events section.' },
  { q: 'how do i get a keynote recording', a: 'Keynote recordings are available in the Events section.' },
  { q: 'how do i get a roundtable recording', a: 'Roundtable recordings are available in the Events section.' },
  { q: 'how do i get a q&a recording', a: 'Q&A recordings are available in the Events section.' },
  { q: 'how do i get a networking event recording', a: 'Networking event recordings are available in the Events section.' },
  { q: 'how do i get a pitch deck review', a: 'Pitch deck reviews are available from mentors and investors.' },
  { q: 'how do i get a business model review', a: 'Business model reviews are available from mentors and investors.' },
  { q: 'how do i get a product review', a: 'Product reviews are available from mentors and investors.' },
  { q: 'how do i get a market review', a: 'Market reviews are available from mentors and investors.' },
  { q: 'how do i get a financial review', a: 'Financial reviews are available from mentors and investors.' },
  { q: 'how do i get a legal review', a: 'Legal reviews are available from mentors and investors.' },
  { q: 'how do i get a technical review', a: 'Technical reviews are available from mentors and investors.' },
  { q: 'how do i get a design review', a: 'Design reviews are available from mentors and investors.' },
  { q: 'how do i get a ux review', a: 'UX reviews are available from mentors and investors.' },
  { q: 'how do i get a ui review', a: 'UI reviews are available from mentors and investors.' },
  { q: 'how do i get a code review', a: 'Code reviews are available from mentors and investors.' },
  { q: 'how do i get a pitch review', a: 'Pitch reviews are available from mentors and investors.' },
];

export default chatbotQA; 