# Generated by Django 5.1.6 on 2025-04-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_crowdfundingcampaign_contribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('raised_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
