# Generated by Django 5.2 on 2025-05-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_control', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
