# Generated by Django 5.2 on 2025-05-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_company_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slide_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
